### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zunichky/tc359_helper_methods#1]
It looks like this is still failing a single spec, due to the Bootstrap alert div containing an extra element that it shouldn't.

```
Failures:

  1) MethodsPracticeHelpers#bootstrap_alert when passed both a message and a type div tag contains exactly 2 elements
     Failure/Error: expect( @alert.children.size ).to eq(2)

       expected: 2
            got: 3

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/bootstrap_alert_spec.rb:75:in `block (5 levels) in <top (required)>'
```

Try comparing the code you're generating to [Bootstrap's documentation](http://getbootstrap.com/components/#alerts-dismissible) to see the difference.

It looks like your code is also missing [the `.rspec` file](https://github.com/chrisvfritz/tc359_helper_methods/blob/master/.rspec), which would make the specs error out when you try to run them. To compensate while fixing this problem, you can just run:

``` bash
bundle exec rspec --require spec_helper --format documentation --color
```

Let me know how this goes. If you get stuck on something, I'll be happy to point you in the right direction.
